Transition generic endpoint to more specific one.
rstudio/rscloud pull request #52
Opened 2022-04-05 20:08 UTC by ssinnott

This transitions the space projects call to a new set of endpoints that are more optimized for handling requests for projects in a space.

This also tweaks a spot in the space serialization where the name of the count has changed.

2022-05-06 03:18 UTC, mine-cetinkaya-rundel requested changes

2022-05-06 03:18 UTC, mine-cetinkaya-rundel commented on R/projects.R
> +  projects <- collect_paginated(response, path = space_project_list_url, query = query_list)
I've tried this with a few of my spaces and I'm getting the same error regardless of whether the space has LOTS of projects or not so many. The issue seems to be that `projects` here returns a list of `NULL`s and so the subsequent pipeline fails.

2022-05-09 20:55 UTC, ssinnott commented
Found it (I think). This seems to work locally but I still see the tests are failing.

```
==> Testing R file using 'testthat'

ℹ Loading rscloud
Using `user_id` column.
Using `user_id` column.

══ Testing test-projects.R ═════════════════════════════════════════════════════

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 1 ]

── Failure (test-projects.R:9:3): project listing works ────────────────────────
`projs` (`actual`) not identical to c("test-project-1", "test-project-2") (`expected`).

`actual`:   "test-project-2" "test-project-1"
`expected`: "test-project-1" "test-project-2"


[ FAIL 1 | WARN 0 | SKIP 0 | PASS 1 ]

Test complete
```

2022-05-20 21:00 UTC, mine-cetinkaya-rundel approved these changes
Looks good to me now!

2022-05-20 21:04 UTC, merged

2022-05-20 21:04 UTC, mine-cetinkaya-rundel commented
I think the test failures are the same issue as before so we'll need to tend to them later, but doesn't need to hold this PR up.